name: Provision Roboshop Infra
on: [workflow_dispatch]
jobs:
#  DEV-PLAN:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v4
#      - name: Terraform Init
#        run: terraform init -backend-config=env-dev/state.tfvars
#      - name: Terraform Plan
#        run: terraform plan -var-file=env-dev/main.tfvars

  DEV-APPLY:
    runs-on: self-hosted
    environment: dev  #for approval
    #needs: DEV-PLAN
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform Apply
        run: terraform apply -var-file=env-dev/main.tfvars -auto-approve

  QA:
    runs-on: self-hosted
    environment: qa  #for approval
    needs: DEV-APPLY
    steps:
      #- uses: actions/checkout@v4 #get the code
      - run: echo demo job for QA

  UAT:
    runs-on: self-hosted
    environment: uat  #for approval
    needs: QA
    steps:
      #- uses: actions/checkout@v4 #get the code
      - run: echo demo job for UAT

  PROD:
    runs-on: self-hosted
    environment: prod  #for approval
    needs: UAT
    steps:
      - uses: actions/checkout@v4 #get the code
      - name: Terraform Init
        run: terraform init -backend-config=env-prod/state.tfvars
